# Generated by Django 4.0.3 on 2022-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='chef_departement',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
