# Generated by Django 4.0.3 on 2022-04-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_professeur_chef_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='chef_departement',
            field=models.BooleanField(default=False),
        ),
    ]
